from __future__ import annotations

from dataclasses import dataclass

from app.schemas.taxonomy import (
    BodyShape,
    Gender,
    GoalTag,
    LegRatio,
    SceneTag,
    ShoulderType,
    StyleTag,
    WaistType,
)


@dataclass(frozen=True)
class CatalogItem:
    name: str
    category: str
    target_gender: Gender
    style_tags: frozenset[StyleTag]
    scene_tags: frozenset[SceneTag]
    goal_tags: frozenset[GoalTag]
    body_shapes: frozenset[BodyShape]
    shoulder_types: frozenset[ShoulderType]
    waist_types: frozenset[WaistType]
    leg_ratios: frozenset[LegRatio]
    popularity: int


def _catalog_item(
    name: str,
    category: str,
    target_gender: Gender,
    style_tags: tuple[StyleTag, ...],
    scene_tags: tuple[SceneTag, ...],
    goal_tags: tuple[GoalTag, ...],
    body_shapes: tuple[BodyShape, ...],
    shoulder_types: tuple[ShoulderType, ...],
    waist_types: tuple[WaistType, ...],
    leg_ratios: tuple[LegRatio, ...],
    popularity: int,
) -> CatalogItem:
    return CatalogItem(
        name=name,
        category=category,
        target_gender=target_gender,
        style_tags=frozenset(style_tags),
        scene_tags=frozenset(scene_tags),
        goal_tags=frozenset(goal_tags),
        body_shapes=frozenset(body_shapes),
        shoulder_types=frozenset(shoulder_types),
        waist_types=frozenset(waist_types),
        leg_ratios=frozenset(leg_ratios),
        popularity=popularity,
    )


CATALOG_ITEMS: tuple[CatalogItem, ...] = (
    _catalog_item(
        name="合身短夹克",
        category="外套",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.KOREAN, StyleTag.MINIMAL, StyleTag.CASUAL),
        scene_tags=(SceneTag.DAILY, SceneTag.CLASS, SceneTag.DATE),
        goal_tags=(GoalTag.TALL,),
        body_shapes=(BodyShape.H, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=84,
    ),
    _catalog_item(
        name="高腰直筒裤",
        category="下装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.MINIMAL, StyleTag.KOREAN, StyleTag.COMMUTE),
        scene_tags=(SceneTag.DAILY, SceneTag.INTERVIEW, SceneTag.CLASS),
        goal_tags=(GoalTag.SLIM, GoalTag.TALL),
        body_shapes=(BodyShape.H, BodyShape.A),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL),
        popularity=90,
    ),
    _catalog_item(
        name="A字裙",
        category="裙装",
        target_gender=Gender.FEMALE,
        style_tags=(StyleTag.SWEET, StyleTag.KOREAN, StyleTag.COMMUTE),
        scene_tags=(SceneTag.DATE, SceneTag.DAILY, SceneTag.CLASS),
        goal_tags=(GoalTag.SLIM,),
        body_shapes=(BodyShape.A, BodyShape.H),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=82,
    ),
    _catalog_item(
        name="垂感阔腿裤",
        category="下装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.MINIMAL, StyleTag.COMMUTE, StyleTag.CHINESE),
        scene_tags=(SceneTag.DAILY, SceneTag.INTERVIEW, SceneTag.DATE),
        goal_tags=(GoalTag.SLIM, GoalTag.COMFORT),
        body_shapes=(BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.NORMAL,),
        leg_ratios=(LegRatio.NORMAL, LegRatio.LONG),
        popularity=88,
    ),
    _catalog_item(
        name="开领衬衫",
        category="上装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.MINIMAL, StyleTag.COMMUTE, StyleTag.KOREAN),
        scene_tags=(SceneTag.INTERVIEW, SceneTag.DATE, SceneTag.DAILY),
        goal_tags=(GoalTag.SLIM,),
        body_shapes=(BodyShape.H, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.WIDE, ShoulderType.MEDIUM),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.NORMAL, LegRatio.LONG),
        popularity=86,
    ),
    _catalog_item(
        name="V领针织",
        category="上装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.KOREAN, StyleTag.MINIMAL, StyleTag.SWEET),
        scene_tags=(SceneTag.DAILY, SceneTag.DATE, SceneTag.INTERVIEW),
        goal_tags=(GoalTag.SLIM, GoalTag.COMFORT),
        body_shapes=(BodyShape.H, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.WIDE,),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=79,
    ),
    _catalog_item(
        name="短款上衣",
        category="上装",
        target_gender=Gender.FEMALE,
        style_tags=(StyleTag.KOREAN, StyleTag.SWEET, StyleTag.CASUAL),
        scene_tags=(SceneTag.DATE, SceneTag.DAILY, SceneTag.TRAVEL),
        goal_tags=(GoalTag.TALL,),
        body_shapes=(BodyShape.H, BodyShape.A),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM),
        waist_types=(WaistType.UNDEFINED,),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL),
        popularity=80,
    ),
    _catalog_item(
        name="深色直筒裤",
        category="下装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.MINIMAL, StyleTag.COMMUTE, StyleTag.CASUAL),
        scene_tags=(SceneTag.DAILY, SceneTag.INTERVIEW, SceneTag.CLASS),
        goal_tags=(GoalTag.SLIM,),
        body_shapes=(BodyShape.A, BodyShape.H),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=87,
    ),
    _catalog_item(
        name="同色系长裤",
        category="下装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.MINIMAL, StyleTag.COMMUTE, StyleTag.CASUAL),
        scene_tags=(SceneTag.DAILY, SceneTag.CLASS, SceneTag.INTERVIEW),
        goal_tags=(GoalTag.TALL,),
        body_shapes=(BodyShape.H, BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT,),
        popularity=76,
    ),
    _catalog_item(
        name="简洁西装外套",
        category="外套",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.COMMUTE, StyleTag.MINIMAL),
        scene_tags=(SceneTag.INTERVIEW,),
        goal_tags=(GoalTag.SLIM, GoalTag.TALL),
        body_shapes=(BodyShape.H, BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=85,
    ),
    _catalog_item(
        name="休闲帆布鞋",
        category="鞋履",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.CASUAL, StyleTag.KOREAN),
        scene_tags=(SceneTag.CLASS, SceneTag.TRAVEL, SceneTag.DAILY),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.H, BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=92,
    ),
    _catalog_item(
        name="轻便休闲套装",
        category="套装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.CASUAL, StyleTag.KOREAN),
        scene_tags=(SceneTag.TRAVEL, SceneTag.DAILY),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.H, BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=83,
    ),
    _catalog_item(
        name="柔和配色针织上衣",
        category="上装",
        target_gender=Gender.FEMALE,
        style_tags=(StyleTag.SWEET, StyleTag.KOREAN),
        scene_tags=(SceneTag.DATE, SceneTag.DAILY),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.H, BodyShape.A),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=75,
    ),
    _catalog_item(
        name="新中式提花上衣",
        category="上装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.CHINESE, StyleTag.MINIMAL),
        scene_tags=(SceneTag.DATE, SceneTag.TRAVEL, SceneTag.DAILY),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.H, BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=73,
    ),
    _catalog_item(
        name="高腰A字半裙",
        category="裙装",
        target_gender=Gender.FEMALE,
        style_tags=(StyleTag.SWEET, StyleTag.COMMUTE, StyleTag.KOREAN),
        scene_tags=(SceneTag.CLASS, SceneTag.DATE, SceneTag.INTERVIEW),
        goal_tags=(GoalTag.SLIM, GoalTag.TALL),
        body_shapes=(BodyShape.A, BodyShape.H),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL),
        popularity=81,
    ),
    _catalog_item(
        name="利落工装裤",
        category="下装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.CASUAL, StyleTag.KOREAN),
        scene_tags=(SceneTag.TRAVEL, SceneTag.DAILY, SceneTag.CLASS),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.H, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.NORMAL,),
        leg_ratios=(LegRatio.NORMAL, LegRatio.LONG),
        popularity=78,
    ),
    _catalog_item(
        name="直筒牛仔裤",
        category="下装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.CASUAL, StyleTag.KOREAN, StyleTag.MINIMAL),
        scene_tags=(SceneTag.DAILY, SceneTag.CLASS, SceneTag.TRAVEL),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.H, BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=89,
    ),
    _catalog_item(
        name="干净针织开衫",
        category="外套",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.SWEET, StyleTag.KOREAN, StyleTag.MINIMAL),
        scene_tags=(SceneTag.DATE, SceneTag.CLASS, SceneTag.DAILY),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.H, BodyShape.A, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=77,
    ),
    _catalog_item(
        name="基础圆领T恤",
        category="上装",
        target_gender=Gender.NEUTRAL,
        style_tags=(StyleTag.MINIMAL, StyleTag.CASUAL),
        scene_tags=(SceneTag.DAILY, SceneTag.CLASS, SceneTag.TRAVEL),
        goal_tags=(GoalTag.COMFORT,),
        body_shapes=(BodyShape.A, BodyShape.H, BodyShape.INVERTED_TRIANGLE),
        shoulder_types=(ShoulderType.NARROW, ShoulderType.MEDIUM, ShoulderType.WIDE),
        waist_types=(WaistType.UNDEFINED, WaistType.NORMAL),
        leg_ratios=(LegRatio.SHORT, LegRatio.NORMAL, LegRatio.LONG),
        popularity=91,
    ),
)
